export enum SORT_WAY {
  DESC = 'DESC',
  ASC = 'ASC',
}

export enum MATCH_RESULT {
  WIN = 'WIN',
  DRAW = 'DRAW',
  LOSS = 'LOSS',
}

export enum MATCH_ACTION_TYPES {
  PARTICIPATION = 'PARTICIPATION',
  GOAL = 'GOAL',
  MISSED_GOAL = 'MISSED_GOAL',
  INJURY = 'INJURY',
  ASSIST = 'ASSIST',
  SAVE = 'SAVE',
  PENALTY_GOAL = 'PENALTY_GOAL',
  PENALTY_SAVE = 'PENALTY_SAVE',
  FOUL = 'FOUL',
  BALL_TACKLE = 'BALL_TACKLE',
  DRIBBLE = 'DRIBBLE',
}
